<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx', models.DecimalField(decimal_places=5, max_digits=5)),
                ('h0', models.DecimalField(decimal_places=5, max_digits=5)),
                ('h1', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Sg0', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Sg1', models.DecimalField(decimal_places=5, max_digits=5)),
                ('A', models.DecimalField(decimal_places=5, max_digits=5)),
                ('B', models.DecimalField(decimal_places=5, max_digits=5)),
                ('C', models.DecimalField(decimal_places=5, max_digits=5)),
                ('x3', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Iteracion', models.IntegerField(max_length=5)),
                ('RaizAnterior', models.DecimalField(decimal_places=5, max_digits=5)),
                ('RaizResultante', models.DecimalField(decimal_places=5, max_digits=5)),
                ('MargenError', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
=======
# Generated by Django 4.2.1 on 2023-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx', models.DecimalField(decimal_places=5, max_digits=5)),
                ('h0', models.DecimalField(decimal_places=5, max_digits=5)),
                ('h1', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Sg0', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Sg1', models.DecimalField(decimal_places=5, max_digits=5)),
                ('A', models.DecimalField(decimal_places=5, max_digits=5)),
                ('B', models.DecimalField(decimal_places=5, max_digits=5)),
                ('C', models.DecimalField(decimal_places=5, max_digits=5)),
                ('x3', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Iteracion', models.IntegerField(max_length=5)),
                ('RaizAnterior', models.DecimalField(decimal_places=5, max_digits=5)),
                ('RaizResultante', models.DecimalField(decimal_places=5, max_digits=5)),
                ('MargenError', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
>>>>>>> adea497916b6fbb42bf4fdedd9214626e0f16cf5
